[package]
name = "htlk-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Parses and compiles Harness Toolkit IR into bytecode"
readme = "README.md"
documentation = "https://docs.rs/htlk-ir"
keywords = ["harness", "compiler", "ir", "toolkit"]
categories = ["compilers", "data-structures"]

[dependencies]
chumsky.workspace = true
logos.workspace = true
miette.workspace = true

[lints]
workspace = true
